# Generated by Django 4.2 on 2023-07-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('observation', models.CharField(max_length=1000)),
                ('conclusion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('Boil', 'Boil'), ('Add', 'Add'), ('Light', 'Light')], max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('chemical', models.CharField(blank=True, choices=[('Water', 'Water'), ('Starch', 'Starch'), ('Sodium Hydroxide', 'Sodium Hydroxide')], max_length=100, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('Beaker', 'Beaker'), ('Bunsen Burner', 'Bunsen Burner'), ('Sunflower Paper', 'Sunflower Paper'), ('Pipette', 'Pipette'), ('Test Tube', 'Test Tube'), ('Lighter', 'Lighter'), ('Test Tube', 'Test Tube')], max_length=100, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='TeacherView.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Beaker', 'Beaker'), ('Bunsen Burner', 'Bunsen Burner'), ('Sunflower Paper', 'Sunflower Paper'), ('Pipette', 'Pipette'), ('Test Tube', 'Test Tube'), ('Lighter', 'Lighter'), ('Test Tube', 'Test Tube')], max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='TeacherView.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Water', 'Water'), ('Starch', 'Starch'), ('Sodium Hydroxide', 'Sodium Hydroxide')], max_length=1000)),
                ('symbol', models.CharField(max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='TeacherView.experiment')),
            ],
        ),
    ]
