# Generated by Django 4.2 on 2023-04-06 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('observation', models.CharField(max_length=1000)),
                ('conclusion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherView.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('دورق', 'دورق'), ('موقد', 'موقد'), ('ورقة عباد شمس', 'ورقة عباد شمس'), ('سحاحة', 'سحاحة'), ('ماصة', 'ماصة'), ('ولاعة', 'ولاعة'), ('انبوبة اختبار', 'انبوبة اختبار')], max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='TeacherView.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ماء', 'ماء'), ('محلول نشا', 'محلول نشا'), ('محلول لوغول', 'محلول لوغول')], max_length=1000)),
                ('symbol', models.CharField(max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='TeacherView.experiment')),
            ],
        ),
    ]
