# Generated by Django 4.2 on 2023-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='name',
            field=models.CharField(choices=[('Water', 'Water'), ('Starch', 'Starch'), ('Sodium Hydroxide', 'Sodium Hydroxide')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('Beaker', 'Beaker'), ('Bunsen Burner', 'Bunsen Burner'), ('Sunflower Paper', 'Sunflower Paper'), ('Pipette', 'Pipette'), ('Test Tube', 'Test Tube'), ('Lighter', 'Lighter'), ('Test Tube', 'Test Tube')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='steps',
            name='equipment',
            field=models.CharField(choices=[('Beaker', 'Beaker'), ('Bunsen Burner', 'Bunsen Burner'), ('Sunflower Paper', 'Sunflower Paper'), ('Pipette', 'Pipette'), ('Test Tube', 'Test Tube'), ('Lighter', 'Lighter'), ('Test Tube', 'Test Tube')], max_length=100),
        ),
    ]
