# Generated by Django 4.2 on 2023-05-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherView', '0003_steps_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='step',
        ),
    ]
